name: sensortag
version: 1.0.5.2
summary: SensorTag Python Bluetooth LE implementation
description: API and command line tools for Python Bluetooth Low Energy access
confinement: strict
grade: stable

apps:
  sensortag:
    command: bin/sensortag
    plugs: [bluetooth-control, network-bind]

parts:
  bluepy:
    plugin: python
    source: https://github.com/IanHarvey/bluepy
    source-type: git
    build-packages: [libglib2.0-dev]
