name: mysensortag
base: core20
version: 1.0.5.3
summary: SensorTag Python Bluetooth LE snap
description: Command line tools for Python Bluetooth Low Energy access
confinement: strict
grade: stable

apps:
  sensortag:
    command: bin/sensortag
    plugs: [bluetooth-control, network]

parts:
  bluepy:
    plugin: python
    source: https://github.com/dbruno74/bluepy.git
    source-tag: SENSORTAG_CC1352R
    source-type: git
    build-packages: 
       - libglib2.0-dev
       - python3-pip
